// Default configurations and one-time legacy import. Runtime rules never inspect game IDs.
const CATALOG_PRESETS=['mtga','hearthstone','might-magic','shadowverse','master-duel','snap','duel-links','pokemon-pocket'];
function presetSchedule(id,weekly=false){const s=RESET_SCHEDULES[id];return {kind:weekly?'weekly':'daily',time:String(weekly?s.weekly.hour:s.daily).padStart(2,'0')+':00',weekday:s.weekly?.day||0,days:1,anchor:'2026-01-01'};}
function presetRule(id,type,label,schedule,extra={}){return {id,type,label,source:'builtin',schedule,spawnCount:1,capacity:3,passExtra:0,rewards:[],quests:[],...extra};}
function presetQuest(id,label,schedule,resources,extra={}){const rewards=resources.map((r,i)=>({id:'r'+i,label:Object.keys(r).length?rewardText(r):'완료',resources:r}));return presetRule(id,'quest',label,schedule,{rewards,quests:[{id:'q',label,rewardIds:rewards.map(x=>x.id)}],...extra});}
function presetGoal(id,label,schedule,target,steps,extra={}){return presetRule(id,'goal',label,schedule,{target,steps,...extra});}
function presetPass(id){const table=PASS_DATA[id];return presetRule('pass','pass','패스',{kind:'once',time:'00:00'},{target:table.max,steps:table.levels.map(x=>({at:x.level,free:x.free,paid:x.paid})),...(table.repeat?{repeat:{from:table.levels.length+1,every:1,free:table.repeat.free,paid:table.repeat.paid}}:{}),attention:'none',...(id==='might-magic'?{end:'2026-09-28T21:26:00+09:00'}:{})});}
function presetCatalog(id){if(id==='kards')return defaultKardsRules();const daily=presetSchedule(id),weekly=RESET_SCHEDULES[id].weekly?presetSchedule(id,true):daily;
 if(id==='mtga')return [presetQuest('daily','일일 퀘스트',daily,[{gold:500,xp:500},{gold:750,xp:500}],{spawnCount:1,initialCount:3,guide:['500골드 일일 퀘스트는 교체 권장','골드 효율은 일일 4승, 일일 XP는 10승까지']}),presetGoal('daily-win','일일 승리',daily,15,Array.from({length:15},(_,i)=>({at:i+1,free:{gold:mtgaWinGold(i+1),xp:mtgaDailyWinXp(i+1)-mtgaDailyWinXp(i),icr:mtgaWinGold(i+1)?0:1}})),{event:'win',eventLabel:'승리 +1',attention:'urgent',window:3}),presetGoal('weekly-win','주간 승리',weekly,15,Array.from({length:15},(_,i)=>({at:i+1,free:{xp:250}})),{event:'win',hideAction:true,attention:'none',totalResource:'xp'})];
 if(id==='hearthstone')return [presetQuest('daily','일일 퀘스트',daily,[{}]),presetQuest('weekly','주간 퀘스트',weekly,[{}],{spawnCount:3,capacity:3,replace:true,attention:'warning'}),presetRule('brawl','claim','선술집 난투',weekly,{capacity:1,rewards:[{id:'pack',label:'시즌 카드팩 받기',resources:{'시즌 카드팩':1}}],attention:'warning'}),presetPass(id)];
 if(id==='might-magic'){
  const once={kind:'once',time:'00:00'},link=points=>({points,links:[{target:'pass-xp',event:'complete',value:'points'}]});
  const dq=presetQuest('daily','일일 퀘스트',daily,[400,500,600].map(gold=>({gold,xp:600})),{links:link().links});dq.quests[0].points=600;
  const heroes=presetQuest('heroes-day','히어로즈 일일',daily,[{xp:600}],{capacity:1,paidOnly:true,replace:true,links:link().links});heroes.quests[0].points=600;
  const weeks=MIGHT_WEEKS.flatMap(([name,normal,paid],i)=>[normal,paid].map((list,track)=>presetQuest(`week-${i}-${track}`,track?'히어로즈 퀘스트':'일반 퀘스트',once,[{xp:3000}],{spawnCount:3,capacity:3,paidOnly:!!track,page:name,links:link().links,quests:list.map(([label],n)=>({id:'q'+n,label,rewardIds:['r0'],points:3000}))})));
  return [dq,presetQuest('weekly','주간 퀘스트',weekly,[{gold:1000},{gold:1500}],{spawnCount:3,replace:true,attention:'warning'}),heroes,presetRule('login','claim','접속 보상 · 수량 미등록',{...daily,time:'04:40'},{capacity:1,rewards:[{id:'record',label:'수령 확인',resources:{}}],attention:'urgent'}),presetGoal('pass-xp','패스 XP',once,1000000,[],{hideAction:true,attention:'none',profileXp:true}),presetPass(id),...weeks];
 }
 if(id==='shadowverse')return [presetQuest('daily','일일 퀘스트',daily,SHADOWVERSE_REWARDS.map(r=>({rupies:r.rupies,redEther:r.redEther})),{spawnCount:3,replace:true}),presetQuest('park-daily','파크 일일',daily,[{keys:1}],{spawnCount:2,capacity:2,replace:true,attention:'urgent',quests:PARK_DAILY_QUESTS.map(q=>({id:q.id,label:q.title,rewardIds:['r0'],points:0}))}),presetGoal('park-points','파크 주간 보상',weekly,100,PARK_MILESTONES.map(m=>({at:m.points,free:{[m.resource]:m.amount}})),{hideAction:true,attention:'none'}),presetQuest('park-weekly','파크 주간',weekly,[{}],{spawnCount:6,capacity:6,replace:true,attention:'warning',stopAt:'park-points',columns:3,span:3,quests:PARK_WEEKLY_QUESTS.map(q=>({id:q.id,label:q.title,rewardIds:['r0'],points:q.points})),links:[{target:'park-points',event:'complete',value:'points'}]})];
 if(id==='master-duel'){
  const once={kind:'once',time:'00:00'},pass=presetPass(id);pass.end='2026-11-06T12:59:00+09:00';pass.page='듀얼 패스';
  return [presetQuest('daily','일일 퀘스트',daily,[{gems:40}],{capacity:9,spawnCount:3,unique:true,chooseType:true,columns:3,span:3,quests:MASTER_DUEL_QUESTS.map((label,i)=>({id:'q'+i,label,rewardIds:['r0']}))}),presetRule('login','claim','로그인',daily,{capacity:1,monthlyLimit:30,rewards:[{id:'gems',label:'20 보석 받기',resources:{gems:20}}],attention:'urgent',page:'로그인'}),pass,presetGoal('dice','다이스랠리 주사위',once,50,[...DICE_FIFTY,...DICE_HUNDRED].map(at=>({at,free:{gems:DICE_HUNDRED.includes(at)?100:50}})),{end:DICE_END,page:'다이스랠리'}),presetGoal('laps','다이스랠리 주회',once,8,Array.from({length:8},(_,i)=>({at:i+1,free:[1,2,3,5].includes(i+1)?{gems:100}:[6,7].includes(i+1)?{legacyTickets:10}:i===3?{'스카레드 하이퍼노바 드래곤 메이트 베이스':1}:{'파죽지세 칭호':1}})),{end:DICE_END,page:'다이스랠리'}),presetQuest('event-tasks','이벤트 미션 · 보상 수량 미등록',once,[{}],{spawnCount:5,capacity:5,page:'다이스랠리',end:DICE_END,quests:['듀얼 10회','듀얼 30회','승리 10회','일반/특수 소환 120회','마법/함정 발동 60회'].map((label,i)=>({id:'q'+i,label,rewardIds:['r0']}))}),...SHOP_ITEMS.map(([label,amount,note],i)=>presetRule('shop-'+i,'claim',label,once,{capacity:1,page:'구입 고려',attention:'none',note,expense:{currency:'gems',amount},rewards:[{id:'record',label:amount+' 보석 구매 기록',resources:{}}]}))];
 }
 if(id==='snap'){
  const slots={...daily,kind:'slots',times:['04:00','12:00','20:00']};return [presetQuest('missions','일반 임무',slots,[{credits:50,seasonXp:25},{credits:100,seasonXp:50}],{spawnCount:2,capacity:6,removeCompleted:true,showEmpty:false,quests:[{id:'normal',label:'일반 임무',rewardIds:['r0']},{id:'hard',label:'어려움 임무',rewardIds:['r1']}],links:[{target:'weekly',event:'complete',value:'one'}]}),presetGoal('weekly','주간 도전',weekly,25,WEEKLY_REWARDS.map((r,i)=>({at:r.count,free:{credits:r.credits,gold:[10,15,25,50,100][i],seasonXp:[100,200,300,500,900][i]}})),{hideAction:true,attention:'none',span:2}),...[[slots,'free-credit','무료 크레딧',{credits:25}],[daily,'free-token','무료 컬렉터 토큰',{tokens:50}],[daily,'web','웹 무료 크레딧',{credits:100}]].map(([schedule,id,label,resources])=>presetRule(id,'claim',label,schedule,{capacity:1,hideCompleted:true,attention:'urgent',rewards:[{id:'receive',label:'수령 확인',resources}]}))];
 }
 if(id==='duel-links'){const quests=DUEL_LINKS_WEEKLY_QUESTS.slice(1);return [presetRule('duelists','resource','일반 듀얼리스트',{kind:'once',time:'00:00'},{capacity:10,intervalMinutes:30,recoverAmount:1,consumeLabel:'듀얼 시작 · 1명 차감',consumeRewards:{}}),presetQuest('weekly','주간 미션',weekly,[{}],{spawnCount:6,capacity:6,replace:true,attention:'warning',span:2,rewards:quests.map((q,i)=>({id:'r'+i,label:q[1],resources:q[3]?{[q[2]]:q[3]}:{}})),quests:quests.map((q,i)=>({id:'q'+i,label:q[0],rewardIds:['r'+i]})),links:[{target:'weekly-all',event:'complete',value:'one'}]}),presetGoal('weekly-all','모든 주간 미션 완료',weekly,6,[{at:6,free:{gems:10}}],{hideAction:true,attention:'none'})];}
 if(id==='pokemon-pocket')return [presetRule('packs','resource','무료 팩',{kind:'once',time:'00:00'},{capacity:2,intervalMinutes:720,recoverAmount:1,consumeLabel:'팩 1개 개봉',consumeRewards:{freePackOpens:1}}),presetRule('points','resource','겟 챌린지 포인트',{kind:'once',time:'00:00'},{capacity:5,intervalMinutes:720,recoverAmount:1,consumeLabel:'포인트 1 사용',consumeRewards:{}}),presetGoal('daily-reward','일일 달성 보상',daily,3,[{at:3,free:{challengeHourglasses:2,packHourglasses:3}}],{hideAction:true,attention:'none'}),presetQuest('daily','일일 미션',daily,[{}],{capacity:7,spawnCount:7,replace:true,completionLimit:3,stopAt:'daily-reward',attention:'urgent',columns:3,span:3,quests:POKEMON_DAILY_MISSIONS.map((label,i)=>({id:'q'+i,label,rewardIds:['r0']})),links:[{target:'daily-reward',event:'complete',value:'one'}]})];
 return [];
}
function importCatalogGame(id,now=new Date()){
 const g=state.games[id];if(g.catalogVersion===1)return;
 const saved=localStorage.getItem('deckroom-quests');if(saved&&!localStorage.getItem('deckroom-backup-catalog'))localStorage.setItem('deckroom-backup-catalog',saved);
 // Synchronize old periods before taking progress; importing never issues a reward.
 syncLegacyGame(id,now);g.ruleCatalog=validateRuleCatalog(presetCatalog(id));g.ruleProgress={};
 const o=rewardOwner(id),put=(rid,values)=>{const r=g.ruleCatalog.find(x=>x.id===rid);if(r)g.ruleProgress[rid]={period:rulePeriod(r,now),missions:[],completed:[],...structuredClone(values)};};
 const queue=(rid,q)=>{const r=g.ruleCatalog.find(x=>x.id===rid);if(!r||!q)return;put(rid,{missions:(q.missions||[]).map((m,i)=>({...catalogMission(r,Math.max(0,r.quests.findIndex(x=>x.label===m.label))),...m,templateId:r.quests.find(x=>x.label===m.label)?.id||r.quests[i%r.quests.length].id,rewardChoices:m.rewardChoices||catalogMission(r,Math.max(0,r.quests.findIndex(x=>x.label===m.label))).rewardChoices})),completed:q.completed||[]});};
 const goal=(rid,value)=>{const r=g.ruleCatalog.find(x=>x.id===rid);if(!r)return;put(rid,{value:value||0,claims:catalogSteps(r).filter(s=>s.at<=value).flatMap(s=>['free',...(g.profile.pass.active?['paid']:[])].map(t=>s.at+'/'+t))});};
 if(id==='mtga'){queue('daily',o.dailyQueue);goal('daily-win',o.dailyWins);goal('weekly-win',o.weeklyWins);g.catalogGuide=['500골드 일일 퀘스트는 교체 권장','골드 효율은 일일 4승, 일일 XP는 10승까지'];}
 const tasks=(rid,done)=>{const r=g.ruleCatalog.find(x=>x.id===rid);if(!r)return;const p={missions:[],completed:[]};catalogSpawn(r,p,r.spawnCount);for(const i of done||[])if(p.missions[i])p.missions[i].done=true;put(rid,p);};
 if(id==='hearthstone'){queue('daily',g.dailyQueue);tasks('weekly',o.weeklyDone);put('brawl',{claimed:g.ledger[`brawl/${weeklyPeriod(id,now)}`]?1:0});}
 if(id==='might-magic'){queue('daily',o.dailyQueue);tasks('weekly',o.weeklyDone);tasks('heroes-day',o.heroesDailyRemaining===false?[0]:[]);put('login',{claimed:o.loginClaimed?1:0});goal('pass-xp',o.passXp);for(let i=0;i<4;i++)for(let track=0;track<2;track++)tasks(`week-${i}-${track}`,(o.weekDone?.[i]||[]).filter(n=>Math.floor(n/3)===track).map(n=>n%3));}
 if(id==='shadowverse'){queue('daily',g.dailyQueue);tasks('park-daily',(o.park.dailyDone||[]).map(x=>PARK_DAILY_QUESTS.findIndex(q=>q.id===x)));tasks('park-weekly',(o.park.weeklyDone||[]).map(x=>PARK_WEEKLY_QUESTS.findIndex(q=>q.id===x)));goal('park-points',o.park.points);}
 if(id==='master-duel'){queue('daily',o.dailyQueue);put('login',{claimed:g.ledger[`login/${dailyPeriod(id,now)}`]?1:0,month:catalogPeriod({schedule:{kind:'monthly'}},now),monthCount:o.loginCount||0});goal('dice',o.event?.dice);goal('laps',o.event?.laps);tasks('event-tasks',o.event?.missions);if(o.eventDeleted)g.ruleCatalog=g.ruleCatalog.filter(r=>!['dice','laps','event-tasks'].includes(r.id));SHOP_ITEMS.forEach(([name],i)=>put('shop-'+i,{claimed:g.profile.currencySpending.some(x=>x.item===name)?1:0}));g.catalogGuide=['클리어하기 어려운 미션은 보관하고 쉬운 3개를 골라 완료하면 편합니다.'];}
 if(id==='snap'){const r=g.ruleCatalog[0];put('missions',{missions:g.generalMissions.map(m=>({...catalogMission(r,m.difficulty==='hard'?1:0),id:m.id})),seed:g.generalMissions.length});goal('weekly',g.weeklyCount);for(const rid of ['free-credit','free-token','web'])put(rid,{claimed:g.ledger[`${rid}/${rid==='free-credit'?snapSlot(now):dailyPeriod(id,now)}`]?1:0});}
 if(id==='duel-links'){put('duelists',{value:o.normalDuelists,clock:o.replenishmentStartedAt??now.getTime()});tasks('weekly',(o.weeklyDone||[]).filter(i=>i>0).map(i=>i-1));goal('weekly-all',(o.weeklyDone||[]).filter(i=>i>0).length);if(!o.weeklyDone.includes(0)&&g.ruleProgress['weekly-all'].value===6)g.ruleProgress['weekly-all'].claims=[];}
 if(id==='pokemon-pocket'){put('packs',{value:o.freePacks,clock:o.lastPackRecoveryAt});put('points',{value:o.getChallengePoints,clock:o.lastChallengeRecoveryAt});tasks('daily',o.dailyDone);goal('daily-reward',o.dailyDone.length);}
 if(PASS_DATA[id])goal('pass',g.profile.pass.level);
 g.catalogVersion=1;syncCatalog(g,now);
}
function syncGame(id,now=new Date()){
 const g=state.games[id];if(!g?.profile?.registeredAt)return;
 if(CATALOG_PRESETS.includes(id)&&!catalogEnabled(id))importCatalogGame(id,now);
 if(catalogEnabled(id)){syncCatalog(g,now);return;}
 syncLegacyGame(id,now);
}
