const test=require('node:test'),assert=require('node:assert/strict'),{start}=require('./harness.cjs');
test('explicit clock synchronizes an inactive game without changing the selected tab',()=>{const a=start();a.select('mtga');a.click('.win-add');a.click('.queued-check');a.click('[data-daily-gold="500"]');a.select('kards');a.run("syncGame('mtga',new Date('2026-09-13T18:00:00+09:00'))");assert.equal(a.run('state.activeGame'),'kards');assert.equal(a.run('state.games.mtga.mtga.dailyWins'),0);assert.equal(a.run('state.games.mtga.mtga.weeklyWins'),0);assert.equal(a.run('state.games.mtga.mtga.dailyQueue.missions.some(m=>m.done)'),false);assert.equal(a.run("totals('mtga').xp"),775);});
test('all five chest tiers retain rarity distinction and exact currency amounts',()=>{const a=start();const expected=[{gold:30,'일반 와일드카드':1},{gold:80,'일반 와일드카드':2,'무작위 일반 골드 카드':2},{gold:150,'한정 와일드카드':3,'무작위 한정 골드 카드':2},{gold:250,'특수 와일드카드':1,'한정 와일드카드':1,'무작위 특수 골드 카드':1,'무작위 등급 미상 골드 카드':2},{gold:350,'정예 와일드카드':1,'특수 와일드카드':1,'한정 와일드카드':1,'무작위 특수 골드 카드':2}];assert.deepEqual(JSON.parse(a.run('JSON.stringify(CHESTS)')),expected);});
test('Hearthstone free and paid pack totals match workbook and weekly brawl never duplicates',()=>{const a=start();a.run("resetGame('hearthstone');state.games.hearthstone.profile.registeredAt=new Date().toISOString();passAwards('hearthstone',100,false,true)");const count=()=>a.run("Object.entries(totals('hearthstone')).filter(([k])=>k.includes('카드팩')).reduce((sum,[,v])=>sum+v,0)");assert.equal(count(),16);a.run("passAwards('hearthstone',100,true,true)");assert.equal(count(),22);a.select('hearthstone');a.click('#brawl');a.click('#brawl');assert.equal(count(),23);a.setTime('2026-09-14T01:00:00+09:00');a.run('refreshActiveQuests()');a.click('#brawl');assert.equal(count(),24);});
test('Might repeat pass rewards apply once per level past100 and never fabricate missing tables',()=>{const a=start();a.run("resetGame('might-magic');passAwards('might-magic',100,true,true)");const previous=a.run("totals('might-magic')['무작위 포일 카드']||0");a.run("passAwards('might-magic',103,true,true);passAwards('might-magic',103,true,true)");assert.equal(a.run("totals('might-magic')['무작위 포일 카드']"),previous+3);const before=a.run("JSON.stringify(totals('shadowverse'))");a.run("passAwards('shadowverse',50,true)");assert.equal(a.run("JSON.stringify(totals('shadowverse'))"),before);});
test('setup rejects stale preview crossing reset, with no reward mutation',()=>{const a=start();a.run("resetGame('mtga');openSetup('mtga')");a.setTime('2026-09-11T17:59:59.999+09:00');a.click('#previewSetup');a.advance(1);a.click('#commitSetup');assert.equal(a.run('state.games.mtga.profile.registeredAt'),null);assert.equal(a.run('Object.keys(state.games.mtga.ledger).length'),0);});
test('muted Duel Links resumes at KST midnight; reset sounds track distinct events',()=>{const a=start();a.select('duel-links');a.run("muteGame('duel-links')");const end=a.run('data().profile.mutedUntil');assert.equal(new Date(end).toISOString(),'2026-09-10T15:00:00.000Z');a.select('snap');a.run("data().profile.alerts.reset=true;updateAlerts('snap')");a.setTime('2026-09-11T04:00:00+09:00');a.run('refreshActiveQuests()');assert.equal(a.run('data().profile.pendingAlerts.length'),1);a.run("acknowledge('snap');refreshActiveQuests()");assert.equal(a.run('data().profile.pendingAlerts.length'),0);a.setTime('2026-09-11T12:00:00+09:00');a.run('refreshActiveQuests()');assert.equal(a.run('data().profile.pendingAlerts.length'),1);});
test('MTGA weekly wins still advance after daily cap and maximum total does not repeat',()=>{const a=start();a.select('mtga');a.run('data().mtga.dailyWins=15;data().mtga.weeklyWins=14');a.click('.win-add');assert.equal(a.run('data().mtga.weeklyWins'),15);assert.equal(a.run("totals('mtga').xp"),250);a.click('.win-add');assert.equal(a.run("totals('mtga').xp"),250);});
test('Might 01:00 and login04:40 periods change at exact millisecond',()=>{const a=start();for(const[hour,minute]of [[1,0],[4,40]]){const at=`2026-09-11T${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}:00+09:00`;a.setTime(new Date(Date.parse(at)-1).toISOString());const old=a.run(`periodAt(${hour},${minute})`);a.advance(1);assert.equal(a.run(`periodAt(${hour},${minute})`),old+1);}});
