const test=require('node:test'),assert=require('node:assert/strict'),{start}=require('./harness.cjs');
for(const id of ['mtga','might-magic'])test(`regression: pre-catalog ${id} completed daily imports without dateKey and reloads once`,()=>{
 const a=start();const saved=a.run(`(()=>{const g=state.games['${id}'];delete g.catalogVersion;delete g.ruleCatalog;delete g.ruleProgress;const o=rewardOwner('${id}');delete o.dailyQueue;if('${id}'==='mtga'){o.dailyQuest=false;o.questReward=750;delete o.dailyQueueExpanded;}else o.dailyRemaining=false;return JSON.stringify(state);})()`);
 const b=start(saved);assert.equal(b.run(`state.games['${id}'].ruleProgress.daily.missions.filter(m=>m.done).length`),1);const total=b.run(`JSON.stringify(totals('${id}'))`);b.run('save()');const c=start(b.saved());assert.equal(c.run(`JSON.stringify(totals('${id}'))`),total);assert.equal(c.run(`state.games['${id}'].ruleProgress.daily.missions.filter(m=>m.done).length`),1);
});
test('regression: initial purchase records expense once, rolls back on failed save, and retries',()=>{
 const a=start();a.run("globalThis.purchase=newUniversalRule('claim');purchase.expense={currency:'gems',amount:100};purchase.initialReceived={[purchase.rewards[0].id]:1};globalThis.write=localStorage.setItem;localStorage.setItem=()=>{throw Error('full')}");assert.throws(()=>a.run("createCustomGame('purchase',[purchase])"));assert.equal(a.run('(state.customGames||[]).length'),0);a.run("localStorage.setItem=write;globalThis.purchased=createCustomGame('purchase',[purchase])");assert.equal(a.run('state.games[purchased].profile.currencySpending[0].amount'),100);assert.equal(a.run('state.games[purchased].profile.activityDays.length'),0);const b=start(a.saved());assert.equal(b.run('state.games[state.customGames[0][0]].profile.currencySpending.length'),1);assert.equal(b.run("(()=>{const id=state.customGames[0][0],r=state.games[id].ruleCatalog[0];return catalogAction(id,r.id,'complete',{reward:r.rewards[0].id});})()"),false);assert.equal(b.run('state.games[state.customGames[0][0]].profile.currencySpending.length'),1);
});
test('regression: edited preset schedule drives header and survives reload',()=>{
 const a=start();a.select('mtga');a.run("const rules=structuredClone(data().ruleCatalog);rules.find(r=>r.id==='daily').schedule.time='10:00';updateCatalog('mtga',rules);renderAll()");assert.match(a.document.querySelector('#resetScheduleInfo').textContent,/매일 10:00 KST/);const b=start(a.saved());assert.match(b.document.querySelector('#resetScheduleInfo').textContent,/매일 10:00 KST/);
});
test('regression: expanded step cache invalidates nested edits and preserves paid late claims',()=>{
 const a=start();a.run("globalThis.r=presetCatalog('might-magic').find(r=>r.type==='pass');globalThis.rows=catalogSteps(r)");assert.equal(a.run('rows.length'),10000);assert.equal(a.run('rows===catalogSteps(r)'),true);a.run('r.steps[0].free.gold=1234');assert.equal(a.run('catalogSteps(r)[0].free.gold'),1234);assert.equal(a.run('rows===catalogSteps(r)'),false);a.run("globalThis.small=newUniversalRule('pass');small.target=2;small.steps=[{at:1,free:{gold:10},paid:{gold:20}},{at:2,free:{gold:30},paid:{gold:40}}];globalThis.pid=createCustomGame('pass',[small]);catalogAction(pid,small.id,'progress',{amount:2});openUniversalSettings(pid)");a.document.querySelector('#universalPaid').checked=true;a.click('#saveUniversalSettings');a.run('openUniversalSettings(pid)');a.click('#saveUniversalSettings');assert.equal(a.run('totals(pid).gold'),100);
});
test('regression: changed reset boundary rebuilds deadline once',()=>{
 const a=start();a.run('globalThis.rebuilds=0;const originalDeadline=rebuildRefreshDeadline;rebuildRefreshDeadline=function(...args){rebuilds++;return originalDeadline(...args)}');a.nextDay();a.run('synchronizeScheduledGames()');assert.equal(a.run('rebuilds'),1);
});
test('F: idle ticks and unchanged focus preserve inputs without serialization or writes',()=>{const a=start();a.setTime('2026-09-11T12:10:00+09:00');a.run('refreshAllGames(true)');a.select('mtga');const input=a.document.querySelector('[data-progress-value]');input.value=7;a.run("globalThis.counts={writes:0,json:0};globalThis.rawWrite=localStorage.setItem;localStorage.setItem=(...args)=>{counts.writes++;return rawWrite(...args)};globalThis.rawJson=JSON.stringify;JSON.stringify=(...args)=>{counts.json++;return rawJson(...args)}");for(let i=0;i<60;i++){a.advance(1000);a.run('refreshAllGames()');}assert.equal(a.run('counts.json'),0);assert.equal(a.run('counts.writes'),0);a.run('refreshAllGames(true)');assert.equal(a.document.querySelector('[data-progress-value]'),input);assert.equal(input.value,'7');});
test('F: a save on another game cannot postpone due quests or full-resource alerts',()=>{const a=start();a.setTime('2026-09-12T03:59:59+09:00');a.run("refreshAllGames(true);state.games.snap.ruleProgress.missions.missions=[];save()");a.advance(1000);a.run("catalogAction('mtga','daily-win','progress',{amount:1});refreshAllGames()");assert.equal(a.run('state.games.snap.ruleProgress.missions.missions.length'),2);a.run("state.games['pokemon-pocket'].profile.alerts.full=true;save();refreshAllGames()");assert.ok(a.run("state.games['pokemon-pocket'].profile.pendingAlerts.some(x=>x.startsWith('resource/'))"));});
test('F: exact next-boundary calculation covers daily weekly interval slots and monthly',()=>{const a=start();for(const schedule of [{kind:'daily',time:'18:00'},{kind:'weekly',time:'01:00',weekday:1},{kind:'intervalDays',time:'09:30',days:3,anchor:'2026-01-01'},{kind:'slots',time:'04:00',times:['04:00','12:00','20:00']},{kind:'monthly',time:'00:00'}]){a.run(`globalThis.rule={schedule:${JSON.stringify(schedule)}};globalThis.time=new Date('2026-09-18T12:00:00+09:00');globalThis.next=nextRuleBoundary(rule,time)`);assert.ok(a.run('next>time.getTime()'));assert.equal(a.run('rulePeriod(rule,new Date(next-1))'),a.run('rulePeriod(rule,time)'));assert.ok(a.run('rulePeriod(rule,new Date(next))>rulePeriod(rule,time)'));}});
test('F: cached totals remain isolated after failed save, retry and game reset',()=>{const a=start();a.select('mtga');a.run("totals('mtga');globalThis.write=localStorage.setItem;localStorage.setItem=()=>{throw Error('full')}");assert.throws(()=>a.run("catalogAction('mtga','daily-win','progress',{amount:1})"));assert.equal(a.run("totals('mtga').gold||0"),0);a.run("localStorage.setItem=write;catalogAction('mtga','daily-win','progress',{amount:1});const result=totals('mtga');result.gold=999");assert.equal(a.run("totals('mtga').gold"),250);a.run("resetGame('mtga')");assert.equal(a.run("totals('mtga').gold||0"),0);});
test('F: due refresh waits for an open editor and resumes after close or clock rollback',()=>{const a=start();a.select('mtga');a.run("openCatalogEditor('mtga')");const content=a.document.querySelector('#questList').innerHTML;a.nextDay();a.run('refreshAllGames()');assert.equal(a.document.querySelector('#questList').innerHTML,content);assert.equal(a.run('refreshViewPending'),true);a.run('closeDialog();refreshAllGames()');assert.equal(a.run('refreshViewPending'),false);a.setTime('2026-09-10T20:00:00+09:00');a.run('refreshAllGames()');assert.ok(a.run('nextRefreshAt>Date.now()'));});
test('paid activation exposes new paid quests once and shared input outlives daily cap',()=>{const a=start();a.run("globalThis.id=createCustomGame('유료 구성',cloneCatalog(presetCatalog('might-magic')));setCatalogBonus(state.games[id],true);globalThis.r=state.games[id].ruleCatalog.find(r=>r.paidOnly);globalThis.n=ruleProgress(state.games[id],r).missions.length;setCatalogBonus(state.games[id],false);setCatalogBonus(state.games[id],true)");assert.ok(a.run('n')>0);assert.equal(a.run('ruleProgress(state.games[id],r).missions.length'),a.run('n'));a.run("catalogAction('mtga','daily-win','progress',{amount:15});state.games.mtga.ruleProgress['weekly-win'].value=0;catalogAction('mtga','daily-win','progress',{amount:1})");assert.equal(a.run("state.games.mtga.ruleProgress['weekly-win'].value"),1);assert.equal(a.run("totals('mtga').gold||0"),750);});
test('failed UI reward can retry once after the screen restores its saved state',()=>{const a=start();a.select('mtga');a.run("globalThis.write=localStorage.setItem;localStorage.setItem=()=>{throw Error('disk full')}");a.click('[data-catalog-action="complete"]');assert.equal(a.run("totals('mtga').gold||0"),0);a.run('localStorage.setItem=write');a.click('[data-catalog-action="complete"]');assert.equal(a.run("totals('mtga').gold"),500);});
test('migration preserves legacy totals, completed goals and repeat-load idempotence',()=>{const a=start();a.run("const g=state.games.mtga;delete g.catalogVersion;delete g.ruleCatalog;delete g.ruleProgress;g.mtga.dailyWins=4;g.mtga.weeklyWins=5;award('mtga','old',{gold:550,xp:1350},'이전 보상',true);save()");const b=start(a.saved());assert.equal(b.run('state.games.mtga.ruleProgress["daily-win"].value'),4);assert.equal(b.run("totals('mtga').gold"),550);b.run("catalogAction('mtga','daily-win','progress',{amount:0})");assert.equal(b.run("totals('mtga').xp"),1350);const c=start(b.saved());assert.equal(c.run("totals('mtga').gold"),550);assert.ok(b.run("localStorage.getItem('deckroom-backup-catalog')"));});
test('all presets clone with remapped links; cycles and missing references are rejected',()=>{const a=start();a.run("for(const id of CATALOG_PRESETS)validateRuleCatalog(cloneCatalog(presetCatalog(id)));globalThis.r=cloneCatalog(presetCatalog('snap'));globalThis.id=createCustomGame('새 게임',r);globalThis.original=state.games.snap.ruleProgress.weekly.value;const m=state.games[id].ruleProgress[r[0].id].missions[0];catalogAction(id,r[0].id,'complete',{mission:m.id,reward:m.rewardChoices[0].id})");assert.equal(a.run('state.games[id].ruleProgress[r[1].id].value'),1);assert.equal(a.run('state.games.snap.ruleProgress.weekly.value'),a.run('original'));assert.throws(()=>a.run("const r=presetCatalog('mtga').slice(1);r[0].links=[{event:'progress',target:r[1].id,value:'one'}];r[1].links=[{event:'progress',target:r[0].id,value:'one'}];validateRuleCatalog(r)"),/순환/);assert.throws(()=>a.run("{const r=presetCatalog('snap');r.pop();r[0].links[0].target='missing';validateRuleCatalog(r)}"),/연동/);});
test('first setup includes initial quest and pass rewards without activity dates',()=>{const a=start();a.run("globalThis.r=presetCatalog('mtga');r[0].initialCount=1;r[0].initialReceived={r1:1};r[1].initialValue=4;r[2].initialValue=5;globalThis.id=createCustomGame('초기 기록',r)");assert.equal(a.run('totals(id).gold'),1300);assert.equal(a.run('totals(id).xp'),1850);assert.equal(a.run('state.games[id].profile.activityDays.length'),0);assert.equal(a.run('state.games[id].ruleProgress.daily.missions.length'),2);a.run("globalThis.p=presetCatalog('master-duel').filter(r=>r.type==='pass');p[0].initialValue=100;globalThis.pid=createCustomGame('패스 초기',p,undefined,{paid:true})");assert.equal(a.run('totals(pid).gems'),1005);});
test('actual editor creates, clones and removes generic rules without source editing',()=>{const a=start();a.select('overview');a.click('#addCustomGame');a.document.querySelector('#customGameName').value='편집 테스트';a.click('#customSetupNext');a.click('[data-new-empty="goal"]');a.click('#createCustomGame');assert.equal(a.run('isCustomGame(state.activeGame)'),true);a.click('#editKardsRules');a.click('#copyRule');a.click('#saveRuleCatalog');assert.equal(a.run('data().ruleCatalog.length'),2);a.click('#editKardsRules');a.click('#removeRule');a.click('#saveRuleCatalog');assert.equal(a.run('data().ruleCatalog.length'),1);});
test('KARDS uses shared goal engine and reset/reload includes custom games',()=>{const a=start();a.run("const r=newUniversalRule('goal');r.steps=[{at:1,free:{gold:20}}];updateCatalog('kards',[r]);catalogAction('kards',r.id,'progress',{amount:1});globalThis.id=createCustomGame('보관',[newUniversalRule('resource')]);save()");assert.equal(a.run("totals('kards').gold"),20);const b=start(a.saved());assert.equal(b.run('state.customGames.length'),1);b.run('resetAllGames()');assert.equal(b.run('GAMES.every(([id])=>!state.games[id].profile.registeredAt)'),true);b.run("const r=defaultKardsRules();r[1].initialReceived={card:2};createCustomGame('KARDS',r,'kards',{paid:true})");assert.equal(b.run("totals('kards').cards"),2);});
test('slots, monthly cap rollover and failed custom creation keep correct state',()=>{const a=start();a.setTime('2026-09-12T03:59:59+09:00');a.run("syncGame('snap');globalThis.before=state.games.snap.ruleProgress.missions.missions.length;state.games.snap.ruleProgress.missions.missions=[]");a.advance(1000);a.run("syncGame('snap')");assert.equal(a.run('state.games.snap.ruleProgress.missions.missions.length'),2);a.run("state.games['master-duel'].ruleProgress.login.monthCount=30");a.setTime('2026-10-01T00:00:00+09:00');a.run("syncGame('master-duel')");assert.equal(a.run("state.games['master-duel'].ruleProgress.login.monthCount"),0);a.run("globalThis.write=localStorage.setItem;localStorage.setItem=()=>{throw Error('disk full')}");assert.throws(()=>a.run("createCustomGame('실패',[])"));assert.equal(a.run('(state.customGames||[]).length'),0);});
